// ✅ Gabkut Pay – Permissions par type de compte
const permissions = {
  standard: {
    canUseWallet: true,
    canSendMoney: true,
    canReceiveMoney: true,
    canWithdraw: true,
    canAccessVirtualCards: true,
    canSuggestFeatures: true,
    canAccessChat: true,
    canAccessGabkutVault: true,
    canUseGabkutLova: true,
    canUseIAQuota: true,
    canUseCoachIA: true,
    canAccessMissions: true,
    canAccessGabkutNetwork: true,
    cardLimit: 1,
  },

  professionnel: {
    canUseWallet: true,
    canSendMoney: true,
    canReceiveMoney: true,
    canWithdraw: true,
    canAccessVirtualCards: true,
    canSuggestFeatures: true,
    canAccessChat: true,
    canAccessGabkutVault: true,
    canUseGabkutLova: true,
    canUseIAQuota: true,
    canUseCoachIA: true,
    canAccessMissions: true,
    canAccessGabkutNetwork: true,
    canCreateProOffers: true,
    canManageMultipleCards: true,
    cardLimit: 5,
  },

  institutionnel: {
    canUseWallet: true,
    canSendMoney: true,
    canReceiveMoney: true,
    canWithdraw: true,
    canAccessVirtualCards: true,
    canSuggestFeatures: true,
    canAccessChat: true,
    canAccessGabkutVault: true,
    canUseGabkutLova: false,
    canUseIAQuota: true,
    canUseCoachIA: true,
    canAccessMissions: false,
    canAccessGabkutNetwork: true,
    canManageMultipleCards: true,
    canViewPayroll: true,
    canPaySalaries: true,
    salaryFees: {
      enseignant: 2.5,
      principal: 3,
      directeur: 3.5,
    },
    cardLimit: 10,
  },

  vip: {
    canUseWallet: true,
    canSendMoney: true,
    canReceiveMoney: true,
    canWithdraw: true,
    canAccessVirtualCards: true,
    canSuggestFeatures: true,
    canAccessChat: true,
    canAccessGabkutVault: true,
    canUseGabkutLova: true,
    canUseIAQuota: true,
    canUseCoachIA: true,
    canAccessMissions: true,
    canAccessGabkutNetwork: true,
    canCreateProOffers: true,
    canManageMultipleCards: true,
    prioritySupport: true,
    cardLimit: 7,
  },

  diaspora: {
    canUseWallet: true,
    canSendMoney: true,
    canReceiveMoney: true,
    canWithdraw: true,
    canAccessVirtualCards: true,
    canSuggestFeatures: true,
    canAccessChat: true,
    canAccessGabkutVault: true,
    canUseGabkutLova: true,
    canUseIAQuota: true,
    canUseCoachIA: true,
    canAccessMissions: true,
    canAccessGabkutNetwork: true,
    canCreateProOffers: true,
    canManageMultipleCards: true,
    canSendToLocal: true,
    cardLimit: 6,
  },

  étudiant: {
    canUseWallet: true,
    canSendMoney: false,
    canReceiveMoney: true,
    canWithdraw: false,
    canAccessVirtualCards: false,
    canSuggestFeatures: true,
    canAccessChat: true,
    canUseGabkutLova: true,
    canUseCoachIA: true,
    canAccessGabkutNetwork: true,
    canAccessMissions: true,
    cardLimit: 1,
  },

  élève: {
    canUseWallet: true,
    canSendMoney: false,
    canReceiveMoney: true,
    canWithdraw: false,
    canAccessVirtualCards: false,
    canSuggestFeatures: true,
    canAccessChat: true,
    canUseGabkutLova: true,
    canUseCoachIA: true,
    canAccessGabkutNetwork: true,
    canAccessMissions: true,
    cardLimit: 0,
  },

  avenir: {
    canUseWallet: false,
    canSendMoney: false,
    canReceiveMoney: true,
    canWithdraw: false,
    canAccessVirtualCards: false,
    canSuggestFeatures: false,
    canAccessChat: false,
    canUseGabkutLova: true,
    canUseCoachIA: false,
    canAccessGabkutNetwork: false,
    cardLimit: 0,
  },

  partagé: {
    canUseWallet: true,
    canSendMoney: true,
    canReceiveMoney: true,
    canWithdraw: true,
    canAccessVirtualCards: true,
    canSuggestFeatures: true,
    canAccessChat: true,
    canUseGabkutLova: true,
    canUseIAQuota: true,
    canAccessGabkutVault: true,
    canAccessGabkutNetwork: true,
    canManageMultipleCards: true,
    cardLimit: 3,
  },
};

export default permissions;
